name: mock
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - fastapi
    - gunicorn
    - python-dateutil
    - python-multipart
    - uvicorn
    - isort
    - pylint
    - pytest
    - pytest-cov
    - requests
    - httpx
    - pydantic==1.10.14
