---
apiVersion: v2
name: knowledge-agents
description: Knowledge Agents Kit Sample Dataspace
home: https://github.com/catenax-ng/product-knowledge/infrastructure
type: application
version: 1.13.21-SNAPSHOT
dependencies:
    - name: postgresql
      version: "15.2.12"
      version: "15.2.12"
      repository: https://charts.bitnami.com/bitnami
    - name: tractusx-connector-azure-vault
      alias: consumer-connector
      repository: https://eclipse-tractusx.github.io/charts/dev
      version: 0.7.3
    - name: agent-plane-azure-vault
      alias: consumer-agent-plane
      version: "1.13.21-SNAPSHOT"
      repository: https://eclipse-tractusx.github.io/charts/dev
    - name: matchmaking-agent
      alias: consumer-agent
      version: "1.13.21-SNAPSHOT"
      repository: https://eclipse-tractusx.github.io/charts/dev
    - name: aas-bridge
      version: "0.13.7-SNAPSHOT"
      repository: https://eclipse-tractusx.github.io/charts/dev

