---
apiVersion: v2
name: knowledge-agents
description: Knowledge Agents Kit Sample Dataspace
home: https://github.com/catenax-ng/product-knowledge/infrastructure
type: application
version: 1.10.2-SNAPSHOT
dependencies:
    - name: postgresql
      version: ">=12.1"
      repository: https://charts.bitnami.com/bitnami

